### PR TITLE
Allow unsetting rfr

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to sgmap/mes-aides-ui#198

### CODE REVIEW

**Comment by MattiSG** [comment]
What about setting `false` rather than `undefined` in the UI?

**Comment by fpagnoux** [comment]
I get an error `CastError: Cast to number failed for value "false" at path "rfr"` when setting it to `false`. I think the model need to be updated if we want to do this.

**Comment by MattiSG** [comment]
Please fix the typo in the commit message (`rft` rather than `rfr`), if we ever need to go back there we'll be happy to have it.

**Comment by fpagnoux** [comment]
Done, is this GTM otherwise ?

**Comment by MattiSG** [comment]
GTM

**Pull request merged**
