### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to #37

### CODE REVIEW

**Comment by MattiSG** [comment]
Does this fix the `kerberos` compilation error on your machine? Do you still need to install a system  package?

**Comment by fpagnoux** [comment]
No, still have to install the package.

**Comment by MattiSG** [comment]
Ok, then this should be documented in the README.

**Comment by fpagnoux** [comment]
I already put it in [mes-aides-ui](https://github.com/sgmap/mes-aides-ui/blob/node012/README.md). 
Should I move it here ?

**Comment by MattiSG** [comment]
Put it in both places. It's unfortunate, but the real dependency is in `mes-aides-api`, yet the install entry point is `mes-aides-ui`.

**Comment by fpagnoux** [comment]
Done.

**Comment by MattiSG** [comment]
GTM

**Comment by fpagnoux** [comment]
Thanks !

**Comment by MattiSG** [comment]
Oh, remember to bump the patch version. Since `master` is protected, do it in this branch first.

**Pull request merged**
