### PR TITLE
Merge sgmap master openfisca next

### PR DESCRIPTION
**Pull request by fpagnoux**
Integrate and relies on #7.

Connected to sgmap/openfisca-france#2.

### CODE REVIEW

**Comment by MattiSG** [comment]
Ok; we'll rebase #7 first, then rebase this, though.

**Comment by MattiSG** [comment]
Rebased.

@fpagnoux Is that enough to pass sgmap/openfisca-france#2?

**Comment by MattiSG** [comment]
@fpagnoux Once again: now that this is merged, can we handle sgmap/openfisca-france#2 or are we still missing updates to reflect in the API?

**Comment by fpagnoux** [comment]
Yes, I think it was the only impact on the api

**Comment by MattiSG** [comment]
:dancer: 

Unfortunately, I think openfisca/openfisca-france#216 will be rebased by @cbenz over openfisca/openfisca-france#217, and we may have to reflect some additional changes. I asked questions to @benjello in openfisca/openfisca-france#217 to define precisely how we're impacted.

**Comment by MattiSG** [comment]
If that's too much work, we'll deploy openfisca/openfisca-france#216 on its own.

**Pull request merged**
