### PR TITLE
Remove CoffeeJS dependency in tests

### PR DESCRIPTION
**Pull request by guillett**

### CODE REVIEW

**Comment by guillett** [comment]
The reason why I have done that change is to remove a dependency that needs to be upgraded. If you prefer, I can bump the package version instead or removing it from package.json

**Comment by MattiSG** [comment]
Well, it seems both costs have been paid for, so I'm pretty agnostic :wink:
I do believe the read/write cost of CS is lower than JS in this specific use case, but if you felt the urge to switch languages that probably means I was wrong. Do whatever you prefer!

**Comment by guillett** [comment]
A brutal attempt to upgrade CS failed but a more subtle (ie. inside the overall package bump) worked. I leave open to close later on.

**Comment by guillett** [comment]
C'était une mauvaise bonne idée. Superseeded by #113

**Pull request closed without merging**
